### PR TITLE
Windows compat after recent changes

### PR DESCRIPTION
**Pull request by fleimgruber**
Fixes str vs bytes with subprocess and re as well as symlinks.  Regression for
direct command line test (skip it).  Drop Python 3.3 and 3.4 from AppVeyor CI.

refs #28

### CODE REVIEW

**Comment by fleimgruber** [comment]
The AppVeyor builds work on 3.5 and 3.6, for 2.7 the symlink loop test fails.  IMHO, this is still an improvement for the situation on Windows, even without full version coverage.

WDYT?

**Comment by brandon-rhodes** [comment]
Looks good for now — thanks!

**Comment by brandon-rhodes** [comment]
What's the link to the Appveyor project, by the way?

**Comment by fleimgruber** [comment]
The URL I am using is https://ci.appveyor.com/project/fleimgruber/uncommitted.

**Comment by brandon-rhodes** [comment]
Thanks! I'll know to refer to it when questions about Windows come up in the future.

**Comment by fleimgruber** [comment]
Feel free to ping me as well in that case and in case I miss it, happy to chime in!

**Pull request merged**
