### PR TITLE
Consider branches which are not checked out too.

### PR DESCRIPTION
**Pull request by AurelienLourot**
Implements issue #7.
All integration tests are passing.

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
In my own patterns of work with `git`, I usually have dozens of branches sitting on my laptop which are purely local, and — if I understand this pull request — it will make `uncommitted` unavoidably noisy for all of the small experimental branches that I create that never grow into anything more than local branches.

But so that `uncommitted` can serve people who make local branches like yours that you do want persisted to remote storage, could we protect this behavior with an option? I think that `-b` might reasonably mean “check for branches that have not been pushed” and could activate the behavior in this pull request. Could you easily revise the pull request to have this logic activated by such an option? Thanks!

**Comment by AurelienLourot** [comment]
This PR will only check if your branches are tracking a remote one and ahead of it. Your "purely local" branches won't be listed here as they are non-tracking branches. 
They will be however listed by PR #10, which I have made optional.

**Comment by AurelienLourot** [comment]
Anything I can do to improve this PR?

**Comment by brandon-rhodes** [comment]
Yes! It needs tests: the `test_integration.py` script needs to create the situation of a remote-tracking branch that has not been pushed, and then confirm that this new version of `uncommitted` can detect it.

I was vaguely planning to someday have enough time to jump in and just write the tests for you, since writing them would also help me review `git` and its output when a branch gets ahead of its remote, but clearly my schedule is keeping me busy enough that I have not yet been able to commit to sitting down and helping out by writing up the rest of the code that the pull request needs. If you could add tests code that shows this works with remote-tracking branches but quietly ignores local branches, then I could review the diff without planning to take on extra coding work myself! Thanks.

**Comment by AurelienLourot** [comment]
You're right, working on it. I'm using this opportunity to use some more advanced pytest features (e.g. fixtures), I hope you'll like it.

**Comment by brandon-rhodes** [comment]
Thank you! Feel free to get rid of the loop where I try to save code while creating 3 different repositories with 3 different tools — it will probably read more simply if the 3 tools have their own different sections of the test file, since from now on they will increasingly diverge in what features we give each of them. I look forward to seeing the results!

**Comment by AurelienLourot** [comment]
I've decided to keep the loop. I haven't touched it much and I think it's still quite readable, as I create the git clones from another fixture anyway. Let me know what you think.

And as you can see I discovered and fixed a tiny bug while writing the tests, so good that you asked for tests :+1:

**Comment by brandon-rhodes** [comment]
Thank you for expanding the tests, @AurelienLourot — I look forward to reviewing this pull request!

I am now done with my keynote at PyCon UK, so I should have time to look at this in the coming week. Thanks again for being willing to do further work on this after my long silence, and hopefully we can get this landed as soon as I have a free half-hour or so!

**Comment by AurelienLourot** [comment]
(BTW, let's not discuss this here, but just in case you haven't seen my e-mail from August 30th: I'd be really happy to become collaborator on this project.)

**Pull request merged**
