### PR TITLE
Follow symlinks when walking.

### PR DESCRIPTION
**Pull request by AurelienLourot**
Implements fix for issue #5.

### CODE REVIEW

**Comment by AurelienLourot** [comment]
Integration tests are still passing.

**Comment by brandon-rhodes** [comment]
The default behavior of Unix / POSIX `find` and of the Python `os.walk()` are to ignore symlinks, and I expect that `uncommitted` users will bring those expectations to its behavior. Could you adjust this behavior to be controlled by a command line option? If this were an opt-in behavior actuated by a `-L` option, then I will be happy to land it. Thanks for the idea, and for the pull request!

**Comment by AurelienLourot** [comment]
Indeed, I've now made it optional.

**Comment by AurelienLourot** [comment]
ping

**Comment by brandon-rhodes** [comment]
(Am finally digging back out after chairing PyCon 2016) —

This looks good! I might tweak the partial thing a bit, but otherwise I think this is useful and well-written. Thanks for contributing!

**Pull request merged**
